import { Shield, Users, Navigation, User } from "lucide-react";
import { Package, Vehicle, AdditionalService } from "./types";

export const packages: Package[] = [
  {
    id: "taxi",
    name: "TAXI / UBER",
    description: "Weekly rental",
    price: "CHF 340 / week",
    extra: "Fully equipped: tachograph, taximeter & taxi light",
    features: [
      "Unlimited kilometers",
      "Comprehensive insurance",
      "BPT-approved vehicle",
    ],
  },
  {
    id: "tourist",
    name: "Tourist rental",
    description: "With or without driver",
    price: "CHF 69 / day",
    features: [
      "100 km per day included",
      "Comprehensive insurance",
      "Attractive discounts for monthly rental",
    ],
  },
  {
    id: "business",
    name: "Business / Corporate clients",
    description: "Daily, weekly, or monthly rental",
    price: "Price on request",
    features: [
      "Customized packages",
      "Comprehensive insurance",
      "Vans for groups",
      "Luxury limousines & executive models",
      "Hybrid & electric vehicles",
      "Offer within 24 hours",
    ],
  },
];

export const vehicles: Vehicle[] = [
  {
    id: "skoda-octavia",
    name: "Skoda Octavia Combi",
    category: "Estate",
    image: "/images/cars/Skoda_Octavia_Combi.webp",
    price: "€25/day",
    seats: 5,
    doors: 5,
    transmission: "Manual",
    fuel: "Petrol",
    airConditioning: true,
    gps: false,
    features: ["Large boot space", "Economical", "Reliable"],
    specs: { engine: "1.4 TSI", consumption: "6.2L/100km", luggage: "610L" },
  },
  {
    id: "mercedes-e",
    name: "Mercedes E-Class",
    category: "Luxury",
    image: "/images/cars/Mercedes_E_Class.webp",
    price: "€55/day",
    seats: 5,
    doors: 4,
    transmission: "Automatic",
    fuel: "Petrol",
    airConditioning: true,
    gps: true,
    features: ["Luxury interior", "Premium sound system", "Leather seats"],
    specs: { engine: "2.0 Turbo", consumption: "7.8L/100km", luggage: "540L" },
  },
  {
    id: "toyota-prius",
    name: "Toyota Prius Hybrid",
    category: "Hybrid",
    image: "/images/cars/Toyota_Prius_Hybrid.webp",
    price: "€35/day",
    seats: 5,
    doors: 5,
    transmission: "Automatic",
    fuel: "Hybrid",
    airConditioning: true,
    gps: true,
    features: ["Eco-friendly", "Excellent fuel economy", "Modern technology"],
    specs: { engine: "1.8 Hybrid", consumption: "3.9L/100km", luggage: "502L" },
  },
  {
    id: "vw-golf",
    name: "Volkswagen Golf",
    category: "Compact",
    image: "/images/cars/VW_Golf.webp",
    price: "€30/day",
    seats: 5,
    doors: 5,
    transmission: "Manual",
    fuel: "Petrol",
    airConditioning: true,
    gps: false,
    features: ["Sporty design", "Easy to park", "Great handling"],
    specs: { engine: "1.5 TSI", consumption: "5.8L/100km", luggage: "380L" },
  },
  {
    id: "skoda-kodiaq",
    name: "Skoda Kodiaq SUV",
    category: "SUV",
    image: "/images/cars/Skoda_Kodiaq_SUV.png",
    price: "€45/day",
    seats: 7,
    doors: 5,
    transmission: "Automatic",
    fuel: "Petrol",
    airConditioning: true,
    gps: true,
    features: ["7 seats", "High driving position", "All-weather capable"],
    specs: { engine: "2.0 TSI", consumption: "8.1L/100km", luggage: "835L" },
  },
  {
    id: "tesla-model3",
    name: "Tesla Model 3",
    category: "Electric",
    image: "/images/cars/Tesla_Model_3.webp",
    price: "€65/day",
    seats: 5,
    doors: 4,
    transmission: "Automatic",
    fuel: "Electric",
    airConditioning: true,
    gps: true,
    features: ["Zero emissions", "Autopilot", "Premium interior"],
    specs: {
      engine: "Electric Motor",
      consumption: "16kWh/100km",
      luggage: "425L",
    },
  },
];

export const additionalServices: AdditionalService[] = [
  {
    id: "insurance",
    name: "Full Insurance Coverage",
    price: "€8/day",
    description: "Complete protection for your rental with zero deductible",
    icon: <Shield className="h-5 w-5" />,
  },
  {
    id: "gps",
    name: "GPS Navigation System",
    price: "€5/day",
    description: "Professional GPS with updated maps and traffic information",
    icon: <Navigation className="h-5 w-5" />,
  },
  {
    id: "childSeat",
    name: "Child Safety Seat",
    price: "€3/day",
    description: "EU-approved child safety seat for children up to 12 years",
    icon: <User className="h-5 w-5" />,
  },
  {
    id: "additionalDriver",
    name: "Additional Driver",
    price: "€10/day",
    description: "Add an extra authorized driver to your rental agreement",
    icon: <Users className="h-5 w-5" />,
  },
];
