import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { freeReader } from "./reader";
import { requiredFieldsProblem } from "./validate";

/**
 * The free reader against clean scans in all three languages.
 *
 * Generated by __fixtures__/makeLetters.mjs: image-only PDFs at 300 DPI with
 * a real QR-bill, the ordinary case. Each must come out with every required
 * field trusted — so that, once its plate is found in the fleet, it goes to
 * the renter with nobody looking. Real scans from the office's pile join
 * this set as they arrive (see docs/FINES-SETUP.md).
 */

const NOW = new Date("2026-10-03T12:00:00Z");

function letter(name: string): Uint8Array {
  return new Uint8Array(readFileSync(join(process.cwd(), "lib/fines/__fixtures__", name)));
}

const GOLDEN = [
  {
    file: "notice-prius-de.pdf",
    language: "de",
    kind: "NOTICE",
    issuerKind: "POLICE",
    fineNumber: "840112233 018 2",
    amountCents: 4000,
    plate: "ZH 513925",
    date: "2026-07-02",
    time: "10:00",
    location: "Kloten, Schaffhauserstrasse",
    offenceCode: "303.1.a",
    dueDate: "2026-10-20",
  },
  {
    file: "reminder-prius-de.pdf",
    language: "de",
    kind: "REMINDER",
    issuerKind: "POLICE",
    fineNumber: "840112233 018 2",
    amountCents: 6000,
    plate: "ZH 513925",
    date: "2026-07-02",
    time: "10:00",
    location: "Kloten, Schaffhauserstrasse",
    offenceCode: "303.1.a",
    dueDate: "2026-10-31",
  },
  {
    file: "notice-octavia-fr.pdf",
    language: "fr",
    kind: "NOTICE",
    issuerKind: "POLICE",
    fineNumber: "4471 2093 55",
    amountCents: 12000,
    plate: "ZH 886530",
    date: "2026-08-14",
    time: "08:15",
    location: "Lausanne, Avenue de Rhodanie",
    offenceCode: "303.1.b",
    dueDate: "2026-10-10",
  },
  {
    file: "notice-octavia-it.pdf",
    language: "it",
    kind: "NOTICE",
    issuerKind: "POLICE",
    fineNumber: "5521 8834 10",
    amountCents: 4000,
    plate: "ZH 886530",
    date: "2026-08-20",
    time: "17:40",
    location: "Lugano, Via Cantonale",
    offenceCode: "303.2.a",
    dueDate: "2026-10-15",
  },
  {
    file: "notice-parkpro-de.pdf",
    language: "de",
    kind: "NOTICE",
    issuerKind: "PRIVATE",
    fineNumber: "PP-2026-118734",
    amountCents: 5000,
    plate: "ZH 401859",
    date: "2026-09-12",
    time: "14:32",
    location: null,
    offenceCode: null,
    dueDate: "2026-10-25",
  },
] as const;

describe("the free reader on clean letters", () => {
  for (const expected of GOLDEN) {
    it(`reads ${expected.file}`, async () => {
      const { extraction: x, language } = await freeReader.read(letter(expected.file), NOW);

      expect(language).toBe(expected.language);
      expect(x.kind).toBe(expected.kind);
      expect(x.issuerKind).toBe(expected.issuerKind);
      expect(x.fineNumber.value).toBe(expected.fineNumber);
      expect(x.amountCents).toMatchObject({ value: expected.amountCents, status: "CONFIRMED" });
      expect(x.plateText.value).toBe(expected.plate);
      expect(x.violationDate).toMatchObject({ value: expected.date, status: "READ" });
      expect(x.violationTime).toMatchObject({ value: expected.time, status: "READ" });
      if (expected.location) expect(x.location.value).toBe(expected.location);
      if (expected.offenceCode) expect(x.offenceCode.value).toBe(expected.offenceCode);
      // The wording wraps onto a second line on the German letters; the
      // renter's email once quoted only the first half.
      if (expected.language === "de" && expected.issuerKind === "POLICE") {
        expect(x.offenceText.value).toBe(
          "Überschreiten allgemeiner, fahrzeugbedingter oder signalisierter Höchstgeschwindigkeit innerorts"
        );
      }
      expect(x.dueDate.value).toBe(expected.dueDate);

      // With the plate found in the fleet, nothing would stop it going out.
      expect(requiredFieldsProblem(x, "CONFIRMED")).toBeNull();
    }, 240_000);
  }
});
